using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Words : MonoBehaviour
{
    
    public List<List<string>> wordList = new List<List<string>>()
    {
        new List<string>(){"Tatil","Plaj","Deniz","Güneþ","Yaz"},
        new List<string>(){"Kitap","Sayfa","Yazar","Kütüphane","Roman"},
        new List<string>(){"Pasta","Tatlý","Krem","Çikolata","Fýrýn"},
        new List<string>(){"Bisiklet","Tekerlek","Pedal","Sürmek","Yol"},
        new List<string>(){"Müzik","Þarký","Enstrüman","Konser","Nota"},
        new List<string>(){"Okul","Öðrenci","Öðretmen","Sýnýf","Ders"},
        new List<string>(){"Bilgisayar","Klavye","Monitör","Fare","Yazýlým"},
        new List<string>(){"Restoran","Menü","Garson","Masa","Yemek"},
        new List<string>(){"Spor","Futbol","Basketbol","Yüzme","Antrenman"},
        new List<string>(){"Uzay","Gezegen","Yýldýz","Gökada","Teleskop"},
        new List<string>(){"Sanat","Resim","Heykel","Galeri","Tuval"},
        new List<string>(){"Yemek","Tarif","Malzeme","Piþirmek","Lezzet"},
        new List<string>(){"Doða","Orman","Dað","Nehir","Göl"},
        new List<string>(){"Þehir","Bina","Cadde","Meydan","Trafik"},
        new List<string>(){"Hava","Bulut","Yaðmur","Kar","Güneþli"},
        new List<string>(){"Astronomi","Teleskop","Gözlem","Uzay","Yýldýz"},
        new List<string>(){"Moda","Tasarým","Defile","Kýyafet","Trend"},
        new List<string>(){"Film","Sinema","Oyuncu","Yönetmen","Senaryo"},
        new List<string>(){"Bilim","Deney","Araþtýrma","Hipotez","Laboratuvar"},
        new List<string>(){"Edebiyat","Þiir","Roman","Yazar","Okumak"},
        new List<string>(){"Gezegen","Mars","Jüpiter","Satürn","Venüs"},
        new List<string>(){"Yazýlým","Programlama","Algoritma","Veritabaný","Kod"},
        new List<string>(){"Tiyatro","Sahne","Oyun","Replik","Kulise"},
        new List<string>(){"Resim","Palet","Fýrça","Renk","Tuval"},
        new List<string>(){"Yaz","Sýcak","Tatil","Deniz","Kumsal"},
        new List<string>(){"Tarih","Müzeler","Antik","Arkeoloji","Sivilizasyon"},
        new List<string>(){"Mutfak","Yemek","Piþirme","Tarif","Baharat"},
        new List<string>(){"Bilim Kurgu","Uzay Gemisi","Robot","Gelecek","Zaman Yolculuðu"},
        new List<string>(){"Kozmetik","Makyaj","Parfüm","Cilt Bakýmý","Güzellik"},
        new List<string>(){"Eðlence","Lunapark","Sinema","Oyun","Konser"},
        new List<string>(){"Fotoðraf","Kamera","Objektif","Poz","Albüm"},
        new List<string>(){"Dans","Bale","Hip-hop","Salsa","Tango"},
        new List<string>(){"Yazý","Kalem","Mürekkep","Kaðýt","Mektup"},
        new List<string>(){"Bahçe","Çiçek","Aðaç","Çim","Saksý"},
        new List<string>(){"Hayvan","Kedi","Köpek","Kuþ","Balýk"},
        new List<string>(){"Gezi","Seyahat","Valiz","Pasaport","Otobüs"},
        new List<string>(){"Gökyüzü","Uçurtma","Yýldýz","Ay","Güneþ"},
        new List<string>(){"Kitapçý","Roman","Dergi","Kalem","Defter"},
        new List<string>(){"Kafe","Kahve","Barista","Fincan","Kek"},
        new List<string>(){"Ofis","Ýþ","Toplantý","Sunum","Bilgisayar"},
        new List<string>(){"Astronomi","Gözlemevi","Uzay","Galaksi","Dürbün"},
        new List<string>(){"Moda","Stil","Koleksiyon","Model","Kumaþ"},
        new List<string>(){"Film","Kamera","Senaryo","Kurgu","Yapýmcý"},
        new List<string>(){"Bilim","Teori","Molekül","Denklem","Atom"},
        new List<string>(){"Edebiyat","Hikaye","Metin","Editör","Yayýnevi"},
        new List<string>(){"Seyahat","Macera","Keþif","Rota","Gidilecek Yerler"},
        new List<string>(){"Müzikal","Sahne Sanatlarý","Orkestra","Libretto","Solist"},
        new List<string>(){"Gastronomi","Þef","Gurme","Lezzetli","Yemek Yarýþmasý"},
        new List<string>(){"Arkeoloji","Kazý","Fosil","Tarih Öncesi","Hieroglif"},
        new List<string>(){"Astronomi","Gökbilim","Uzay Araþtýrmasý","Teleskop","Gözlem"},
        new List<string>(){"Bitki","Çiçek","Yaprak","Dal","Kök"},
        new List<string>(){"Deniz","Kum","Dalga","Mercan","Plaj"},
        new List<string>(){"Yemek","Sofra","Kaþýk","Tabak","Tencere"},
        new List<string>(){"Okuma","Kitap","Gözlük","Lamba","Raf"},
        new List<string>(){"Yazma","Dolmakalem","Defter","Silgi","Masa"},
        new List<string>(){"Kamp","Ateþ","Çadýr","Doða","Yürüyüþ"},
        new List<string>(){"Sinema","Film","Koltuk","Perde","Bilet"},
        new List<string>(){"Kitap","Kütüphane","Okumak","Yazar","Sayfa"},
        new List<string>(){"Konsol","Oyun","Kumanda","Ekran","Eðlence"},
        new List<string>(){"Resim","Tuval","Boya","Fýrça","Sanat"},
        new List<string>(){"Orman","Aðaç","Doða","Kamp","Yaban Hayatý"},
        new List<string>(){"Okyanus","Dalga","Kum","Mercan","Deniz Yýldýzý"},
        new List<string>(){"Gökyüzü","Bulut","Güneþ","Ay","Yýldýz"},
        new List<string>(){"Mutfak","Ocak","Bulaþýk","Tava","Kaþýk"},
        new List<string>(){"Bahar","Çiçek","Kelebek","Arý","Polen"},
        new List<string>(){"Ev","Pencere","Kapý","Çatý","Balkon"},
        new List<string>(){"Ulaþým","Otobüs","Tren","Uçak","Taksi"},
        new List<string>(){"Yiyecek","Meyve","Sebze","Et","Tatlý"},
        new List<string>(){"Ýþ","Ofis","Toplantý","Rapor","Sunum"},
        new List<string>(){"Eðitim","Okul","Üniversite","Öðrenci","Ders"},
        new List<string>(){"Kütüphane","Kitap","Raf","Okuma","Bilgi"},
        new List<string>(){"Bahçe","Bitki","Çiçek","Aðaç","Toprak"},
        new List<string>(){"Mutfak","Yemek","Piþirme","Tarif","Malzeme"},
        new List<string>(){"Spor","Egzersiz","Fitness","Koþu","Yoga"},
        new List<string>(){"Teknoloji","Bilgisayar","Yazýlým","Donaným","Ýnternet"},
        new List<string>(){"Gezgin","Rota","Pusula","Harita","Keþif"},
        new List<string>(){"Kýþ","Kar","Soðuk","Kazak","Þömine"},
        new List<string>(){"Yazýcý","Mürekkep","Kaðýt","Tarama","Fotokopi"},
        new List<string>(){"Çiçekçi","Buket","Gül","Saksý","Fidan"},
        new List<string>(){"Aþçý","Mutfak","Tarif","Tava","Fýrýn"},
        new List<string>(){"Kütüphane","Kitap","Raf","Okuma","Bilgi"},
        new List<string>(){"Bahçe","Bitki","Çiçek","Aðaç","Toprak"},
        new List<string>(){"Mutfak","Yemek","Piþirme","Tarif","Malzeme"},
        new List<string>(){"Spor","Egzersiz","Fitness","Koþu","Yoga"},
        new List<string>(){"Teknoloji","Bilgisayar","Yazýlým","Donaným","Ýnternet"},
        new List<string>(){"Gemi","Deniz","Kaptan","Dalga","Yelken"},
        new List<string>(){"Orman","Aðaç","Kamp","Doða","Yürüyüþ"},
        new List<string>(){"Dað","Týrmanýþ","Zirve","Kar","Manzara"},
        new List<string>(){"Gökyüzü","Uçurtma","Bulut","Güneþ","Ay"},
        new List<string>(){"Yemek","Tarif","Fýrýn","Tatlý","Baharat"},
        new List<string>(){"Spor","Futbol","Basketbol","Yüzme","Koþu"},
        new List<string>(){"Müzik","Nota","Þarký","Enstrüman","Konser"},
        new List<string>(){"Resim","Tuval","Boya","Fýrça","Palet"},
        new List<string>(){"Dans","Müzik","Ritim","Adým","Bale"},
        new List<string>(){"Tiyatro","Sahne","Oyuncu","Replik","Perde"},
        new List<string>(){"Film","Sinema","Yönetmen","Oyuncu","Senaryo"},
        new List<string>(){"Kitap","Yazar","Sayfa","Kapak","Okumak"},
        new List<string>(){"Bilgisayar","Klavye","Ekran","Fare","Yazýlým"},
        new List<string>(){"Telefon","Arama","Mesaj","Uygulama","Ekran"},
        new List<string>(){"Fotoðraf","Kamera","Poz","Çekim","Albüm"},
        new List<string>(){"Araba","Motor","Tekerlek","Yol","Sürüþ"},
        new List<string>(){"Uçak","Pilot","Havaalaný","Bilet","Uçuþ"},
        new List<string>(){"Otobüs","Durak","Yolcu","Bilet","Seyahat"},
        new List<string>(){"Tren","Ray","Vagon","Ýstasyon","Bilet"},
        new List<string>(){"Bisiklet","Pedal","Zincir","Tekerlek","Yol"},
        new List<string>(){"Yanardað", "Patlama", "Lavan", "Krater", "Duman"},
        new List<string>(){"Sel", "Yaðmur", "Nehir", "Taþkýn", "Su baskýný"},
        new List<string>(){"Çöl", "Kum", "Sýcak", "Güneþ", "Deve"},
        new List<string>(){"Buz Daðý", "Soðuk", "Kar", "Penguen", "Kutup"},
        new List<string>(){"Aslan", "Kral", "Yele", "Pençe", "Vahþi"},
        new List<string>(){"Fil", "Hortum", "Gözdiþi", "Afrika", "Savana"},
        new List<string>(){"Yunus", "Balýk", "Okyanus", "Zýplayýþ", "Akýllý"},
        new List<string>(){"Köpek", "Havlama", "Sahip", "Tasma", "Sadýk"},
        new List<string>(){"Pizza", "Hamur", "Peynir", "Domates", "Fýrýn"},
        new List<string>(){"Dondurma", "Soðuk", "Lezzetli", "Külah", "Çikolata"},
        new List<string>(){"Makarna", "Sos", "Spagetti", "Noodle", "Tavuk"},
        new List<string>(){"Börek", "Yufka", "Peynir", "Ispanak", "Fýrýn"},
        new List<string>(){"Telefon", "Arama", "Mesaj", "Uygulama", "Ekran"},
        new List<string>(){"Bilgisayar", "Klavye", "Fare", "Ekran", "Yazýlým"},
        new List<string>(){"Araba", "Motor", "Tekerlek", "Yol", "Sürüþ"},
        new List<string>(){"Bisiklet", "Pedal", "Zincir", "Tekerlek", "Yol"},
        new List<string>(){"Okumak", "Kitap", "Sayfa", "Yazý", "Bilgi"},
        new List<string>(){"Yazmak", "Kalem", "Kaðýt", "Defter", "Mürekkep"},
        new List<string>(){"Konuþmak", "Ses", "Kelime", "Dil", "Sohbet"},
        new List<string>(){"Dinlemek", "Kulak", "Ses", "Müzik", "Anlamak"},
        new List<string>(){"Astronot", "Uzay", "Roket", "Ay", "Dünya"},
        new List<string>(){"Doktor", "Hastane", "Hasta", "Ameliyat", "Ýlaç"},
        new List<string>(){"Öðretmen", "Okul", "Ders", "Öðrenci", "Sýnav"},
        new List<string>(){"Müzisyen", "Enstrüman", "Þarký", "Nota", "Konser"},
        new List<string>(){"Ressam", "Resim", "Tuval", "Boya", "Fýrça"},
        new List<string>(){"Sporcu", "Spor", "Oyun", "Maç", "Kazanmak"},
        new List<string>(){"Oyuncu", "Tiyatro", "Film", "Sahne", "Rol"},
        new List<string>(){"Þarkýcý", "Ses", "Müzik", "Þarký", "Sahne"},
        new List<string>(){"Yazar", "Kitap", "Hikaye", "Roman", "Makale"},
        new List<string>(){"Gezgin", "Seyahat", "Dünya", "Keþif", "Yolculuk"},
        new List<string>(){"Doktor", "Hastane", "Hasta", "Ameliyat", "Ýlaç"},
        new List<string>(){"Öðretmen", "Okul", "Ders", "Öðrenci", "Sýnav"},
        new List<string>(){"Mühendis", "Makine", "Proje", "Tasarým", "Yapý"},
        new List<string>(){"Avukat", "Hukuk", "Mahkeme", "Dava", "Müvekkil"},
        new List<string>(){"Araba", "Motor", "Tekerlek", "Yol", "Sürüþ"},
        new List<string>(){"Bisiklet", "Pedal", "Zincir", "Tekerlek", "Yol"},
        new List<string>(){"Motosiklet", "Hýz", "Motor", "Kask", "Yol"},
        new List<string>(){"Uçak", "Pilot", "Havaalaný", "Bilet", "Uçuþ"},
        new List<string>(){"Ev", "Oda", "Pencere", "Kapý", "Bahçe"},
        new List<string>(){"Okul", "Derslik", "Öðretmen", "Öðrenci", "Sýnýf"},
        new List<string>(){"Hastane", "Doktor", "Hasta", "Ameliyat", "Odasý"},
        new List<string>(){"Market", "Alýþveriþ", "Ürün", "Fiyat", "Kasa"},
        new List<string>(){"Yemek", "Açlýk", "Doymak", "Lezzet", "Tat"},
        new List<string>(){"Uyumak", "Yatak", "Rüya", "Uyku", "Dinlenme"},
        new List<string>(){"Konuþmak", "Ses", "Kelime", "Dil", "Sohbet"},
        new List<string>(){"Dinlemek", "Kulak", "Ses", "Müzik", "Anlamak"},
        new List<string>(){"Mutluluk", "Gülümsemek", "Eðlence", "Sevinç", "Keyif"},
        new List<string>(){"Üzüntü", "Aðlamak", "Keder", "Yas", "Hüzün"},
        new List<string>(){"Öfke", "Sinir", "Kýzgýnlýk", "Patlama", "Baðýrmak"},
        new List<string>(){"Korku", "Endiþe", "Kaygý", "Tedirginlik", "Panik"},
        new List<string>(){"Zaman", "Saat", "Dakika", "Saniye", "Geçmiþ"},
        new List<string>(){"Mekan", "Yer", "Konum", "Uzay", "Dünya"},
        new List<string>(){"Hayat", "Doðum", "Ölüm", "Varlýk", "Yokluk"},
        new List<string>(){"Aþk", "Sevgi", "Sevgi", "Duygu", "Kalp"},



    };
}
